backend/django/post/urls.py
from django.urls import path
from .views import *

app_name="post"

urlpatterns=[
    path('', Home.as_view() , name="home"),
    path('faceRatioIn/', face_ratio_in, name='face_ratio_in'),
    path('faceRatioIn/faceRatioOut', face_ratio_out, name='face_ratio_out'),
    path('personalColorIn/', personal_color_in, name='personal_color_in'),
    path('personalColorIn/personalColorOut', personal_color_out, name='personal_color_out'),


    path('profile', Myprofile.as_view(), name='post_profile'),


    path('search', post_list, name="post_list"),
    path('search_1', post_search, name="post_search"),
    path('mysite/<int:pk>/', mysite_pk, name='post_profile_pk'),
    path('<int:pk>/', post_detail, name='post_detail'),
    path('delete/<int:pk>/',post_delete,name='post_delete'),
    path('edit/<int:pk>/',post_edit,name='post_edit'),

    path('like',post_like,name='post_like'),
    path('reference', post_reference, name='post_reference'),

    path('comment/new',comment_new, name='comment_new'),
    path('comment/delete',comment_delete, name='comment_delete'),

    path('new/<word>', post_new, name='post_new'),
    path('imginput/',image_input, name='image_input'),
    path('imginput/imgprocess',image_process, name='image_process'),
    path('imgoutput',image_output, name='image_output'),
]

backend/django/post/models.py
from django.conf import settings
from django.db import models
from imagekit.models import ProcessedImageField # 이미지 불러오기
from imagekit.processors import ResizeToFill # 사이즈 조절
import re
def photo_path(instance, filename):
    from time import strftime
    from random import choice
    import string
    arr = [choice(string.ascii_letters) for _ in range(8)] # 난수 8글자 랜덤으로 지정
    pid = ''.join(arr)
    extension = filename.split('.')[-1]
    return '{}/{}/{}.{}'.format(strftime('post/%Y/%m/%d/'), instance.author.username, pid, extension) # 업로드 파일 저장 위치

class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    photo = ProcessedImageField(upload_to=photo_path,
                                processors=[ResizeToFill(600,600)], ## 이미지 사이즈 600, 600
                                format = 'JPEG',  # 파일 확장자 JPEG
                                options={'qualty':90})
    like_user_set = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                            blank=True,
                                            related_name='like_user_set',
                                            through='Like') # like_user_set 을 통해서 post.like_user_set 으로 접근이 가능하게


    reference_user_set = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                            blank=True,
                                            related_name='reference_user_set',
                                            through='Reference') # like_user_set 을 통해서 post.like_user_set 으로 접근이 가능하게
            


    content = models.CharField(max_length=255, help_text="최대길이 255자 입력이 가능합니다.", blank=True) # 컨텐츠 입력
    tema = models.CharField('테마',max_length=255, help_text="테마를 입력해주세요,  #테마",blank=True) #테마 입력
    #tema_set = models.ManyToManyField('tema',blank=True)
    cosmetic = models.CharField('화장품',max_length=255, help_text="사용한 화장품을 입력해주세요, #제품명", blank=True) # 화장품 입력
    created_at = models.DateTimeField(auto_now_add=True) # 최초 저장시에만 현재 날짜를 적용
    updated_at = models.DateTimeField(auto_now=True) # 현재 일시 세팅

    class Meta:
        ordering = ['-created_at']
    
#    def tema_save(self):
#        temas = re.findall(r'#(\w+)\b', self.tema,self.cosmetic)

#        if not temas:
#            return
#        for t in temas:
#            tema, tema_created = Tema.objects.get_or_create(name=t)
#            self.tema_set.add(tema)

    @property # 데코레이터 힘들마ㅣㅇ너ㅣ아ㅓ
    def like_count(self):
        return self.like_user_set.count()
    
    @property
    def Reference_count(self):
        return self.reference_user_set.count()

    def __str__(self):
        return self.content

class Like(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE) #유저 삭제되면 라이크도 삭제
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True) #생성
    updated_at = models.DateTimeField(auto_now=True) #업데이트

    class Meta:
        unique_together =(
            ('user', 'post') #유저와 포스트의 유니크한 관계를 맺어줌
        )

class Reference(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE) #유저 삭제되면 라이크도 삭제
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True) #생성
    updated_at = models.DateTimeField(auto_now=True) #업데이트
    class Meta:
        unique_together =(
            ('user', 'post') #유저와 포스트의 유니크한 관계를 맺어줌
        )

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.CharField(max_length=80)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['created_at']

    def __str__(self):
        return self.content

class Tema(models.Model):
    name = models.CharField(max_length=140, unique=True)

    def __str__(self):
        return self.name

backend/django/post/templates/post/comment_new_ajax.html
<div class="comment-detail" id="comment{{ comment.id }}">
    <div class="nick_name"><img src="{{ comment.author.profile.picture.url }}"> {{comment.author.profile.nickname}} {{comment.content}}</div>
    {% if user == comment.author %}
    <input type="button" class="del-comment" data-name="comment_delete" value="삭제" name="{{ comment.id }}">
    {% endif %}
    
</div>

backend/django/post/templates/post/faceRatioOutput.html
{% extends "post/base.html" %}
{% load static %}

<script>
    function rs(){
        for (i=0; i<7; i++){
            document.write(fr_key[i], fr_value[i]);
            //fr_key[i], fr_value[i]
        }
    }:
</script>

{% block content %}
    <link rel="stylesheet" href="{% static 'css/imgprocess.css' %}"/>
    <div class="user-image-container">
        <div class="face-ratio">
            <img id="showImg" src="{% static where %}" class="thumnail">
            {% comment %} <img id="showImg" src="{% static 'img/fr_result.jpg' %}" class="thumnail"> {% endcomment %}
        </div>
    </div>

    {% comment %} 결과물 출력하기 + CSS 입히기 {% endcomment %}
    <div class="contain_ratio">
        <div class="ratio_grid">
            {% for k in fr_key %}
            <div class="ratio_key">
                {{k}}
            </div>
            {% endfor %}
        </div>
        <div class="ratio_grid">
            {% for k in fr_value %}
        <div class="ratio_value">       
                {{k}}
        </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

backend/django/post/templates/post/file_ajax.html
<script type="text/javascript">
(function(){
    const delegation = document.querySelector('input[type=file]');
    const show = document.querySelector('#btn');

    function delegationFunc(e) { // 클릭한거 인자로 받음
        let elem = e.target;
        console.log(elem);
        console.log(elem.accept)
        console.log(elem.checkValidity())
        while(!elem.getAttribute('data-name')){
            elem = elem.parentNode;

            if (elem.nodeName == 'BODY'){
                elem = null;
                return;
            }
        }if(elem.matches('#id')){
            var pk = elem.getAttribute('name');

            $.ajax({
                type: "POST",
                url: "{% url 'accounts:follow' %}",
                data: {
                    'pk': pk,
                    'csrfmiddlewaretoken': '{{ csrf_token}}',
                },
                dataType: "json",
                success: function(response){
                    if(response.status){
                        document.querySelector('input.follow[name=\''+pk+'\']').value="Following";
                    }else{
                        document.querySelector('input.follow[name=\''+pk+'\']').value="Follow";
                    }
                },
                error: function(request, status, error){
                    alert("로그인을 해주세요");
                }
            })

        }

        elem.classList.toggle('on');
    }


    delegation.addEventListener('click',delegationFunc);

})();//익명함수 문서가 로드된후에 자바스크립트가 작동한다.

</script>

backend/django/post/templates/post/home.html
{% extends 'post/base.html' %}
{% load static %}

{% block content %}
<div class="banner home">
  <!--<img src="{% static 'img/simm.jpg' %}" alt="">-->
</div>
<a href="{% url 'post:image_input' %}"><div class="wordcloud">
  <p class="main_title">
    AI MAKEUP TRANSFER
    <br>
    ETCHING
  </p>
 <img src="{% static 'img/shadow.jpg' %}" alt="">
</div></a>
<div class="faceAnalysis">
  <div class="tone">
    <p class="FA_title">
      퍼스널 컬러 진단
    </p>
    <a href="{% url 'post:personal_color_in' %}"><img src="{% static 'img/facetone.png' %}" alt=""></a>
  </div>
  <div class="simillar">
    <p class="FA_title">
      얼굴 비율 완전 분석
    </p>
    <a href="{% url 'post:face_ratio_in' %}"><img src="{% static 'img/faceanalysis.png' %}" alt=""></a>
  </div>
</div>
<div class="banner Event">
  <a href="https://blog.naver.com/PostList.nhn?blogId=handuelly"><img src="{% static 'img/hdly_banner.png' %}" alt=""></a>
</div>
<div class="banner AD">
</div>
{% endblock %}

backend/django/post/templates/post/imginput.html
{% extends 'post/base.html' %}
{% load static %}

{% block content %} 
<form method="POST" action="imgprocess" enctype="multipart/form-data">{% csrf_token %}
    <div class="file-upload">

        <!-- Source Image Area -->
        <div class="srcimg-upload-wrap">
            <input class="file_upload_input_src" type='file' name="srcimg" id="srcimg" onchange="srcURL(srcimg);" accept=".jpg,.png" required>
            <div class="defaut-upload-image">
                <a class="text_center"><img src="{% static 'img/upload_srcimg.PNG' %}" width=80% class="img_center" />내 사진</a>
            </div>
        </div>
        <div class="file-upload-content_src">
            <img class="file-upload-image_src" src="#" alt="your image" />
            <button type="button" onclick="removeUpload_src()" class="remove-srcimg">Remove</button>
        </div>

        <!-- Reference Image Area -->
        <div class="refimg-upload-wrap">
            <input class="file_upload_input_ref" type='file' name="refimg" id="refimg" onchange="refURL(refimg);" accept=".jpg,.png" required>
            <div class="defaut-upload-image">
                <a class="text_center"><img src="{% static 'img/upload_refimg.PNG' %}" width=80% class="img_center" />메이크업 사진</a>
            </div>
        </div>
        <div class="file-upload-content_ref">
            <img class="file-upload-image_ref" src="#" alt="your image" />
            <button type="button" onclick="removeUpload_ref()" class="remove-refimg">Remove
                <span class="image-title"></span></button>
        </div>
        <div class="guide_text">
        MAKEUP TRANSFER<br>
        1500 * 1500 이하 사이즈의 사진을 사용해 주세요<br>
        원하는 사진의 화장을 내 사진으로 옮겨옵니다.<br>
        1. 화장을 입히고 싶은 내 사진을 넣어주세요.<br>
        2. 원하는 메이크업의 사진을 넣어주세요.<br>
        3. show result!<br>
        </div> 
        <input type="submit" class="file-upload-btn-submit" value="Show Result" />
    </div>
</form>
{% endblock %}

backend/django/post/templates/post/myprofile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'base.css'%}">
<div class="profile_container">
    <div class="profile_text">
        <div>
            닉네임 : {{ user_profile.nickname }}
        </div>
        <div>
            피부톤 : {{ user_profile.skinton }}
        </div>
        <div>
            성별 : {{ user_profile.gender}}
        </div>
        <div>
            <button class="followBtn">
                follow
            </button>
        </div>
    </div>
    {% if user_profile %}
        <div class="profile_img"><img src="{{ user_profile.picture.url }}" class="img-responsive thumbnail"></div>
    {% else %}
    <div class="profile_img"><img src="{% static 'img/noprofile.png' %}" class="img-responsive thumbnail"></div>
    {% endif %}
</div>
<div class="extra_txt">
    {{ user_profile.about }}
</div>
<div class="social_status">
    <div class="s_status follower">
        FLLOWERS<br>2000 
    </div>
    <div class="s_status following">
        FOLLOWING<br>2000
    </div>
    <div class="s_status reference">
        REFERENCE<br>2000
    </div>
</div>
<div class="tagbox">
    <div class="tag my" onclick="changeCategory(this)" onmouseout="changeCategory2(this)">
       MY   
    </div>
    <div class="tag like" onclick="changeCategory(this)" onmouseout="changeCategory2(this)">
        LIKE
    </div>
    <div class="tag ref" onclick="changeCategory(this)" onmouseout="changeCategory2(this)">
        REFERENCE
    </div>
</div>

<div class="imgGrid">
    {% for post in posts %}
    {% if user_profile.user == post.author %}
        <img src="{{ post.photo.url }}">
    {% endif %}
    {% endfor %}
</div>
<script>
    function changeCategory(obj){
        obj.style.border = 'solid 1px rgba(133, 128, 128, 0.8)';
        obj.style.borderBottom = 'none';
    }
    function changeCategory2(obj){
        obj.style.border = 'none'; 
    }
</script>
{% endblock %}

backend/django/post/templates/post/personalColorOutput.html
{% extends "post/base.html" %}
{% load static %}

{% block content %}
    <!-- beautyapp_merged > post > templates > post > personalColor_output.html -->
    <link rel="stylesheet" href="{% static 'css/imgprocess.css' %}"/>
    <div class="user-image-container" style="border-radius:30%;">
        <img id="showImg" src="{% static show %}" class="thunail">
        <p>사진에서 추출한 피부색은 다음과 같습니다.</p>
         <div class="Pcolor" style="margin:auto;">
            <div>턱</div>
            <div>왼쪽 뺨</div>
            <div>오른쪽 뺨</div>
            <div>코</div>
            <div>눈썹사이</div>
        </div>
        <div class="color_chart">
            <img id="showImg" src="{% static where %}" style="margin:auto;">
        </div> 
    <p>색을 분석했을때 {{pc_result}}</p>
    </div>

    {% comment %} 결과물 출력하기 + CSS 입히기 {% endcomment %}

{% endblock %}

backend/django/post/templates/post/post_detail.html
{% extends 'post/base.html' %}
{% load static %}

{% block content %}
<div class="detailContainer">

    <div class="postContainer">
        <div class="userinfo">
            <div class="userprofileimg">
                {% if post.author.profile.picture %}
                <a href="{% url 'post:post_profile_pk' post.author.pk %}"><img
                        src="{{ post.author.profile.picture.url }}"></a>
                {% else %}
                <a href="{% url 'post:post_profile_pk' %}"><img
                        src="{% static 'img/noprofile.png' %}"></a>
                {% endif %}
            </div>
            <div class="userid">
            {{ post.author.profile.nickname }}
            </div>
            {% if post.author == user %}
            <div class="dropdown">
                <div id="popupmenu-wrapper">
                    <ul id="popupmenu">
                        <li class="popupmenu-item">
                            <ul class="popupmenu-menu">
                                <div>
                                    <a class="post-edit" href="{% url 'post:post_edit' post.pk %}">수정</a>
                                </div>
                                <div>
                                    <form class="post-delete-form" action="{% url 'post:post_delete' post.pk %}"
                                        method="post">
                                        {% csrf_token %}
                                        <input type="submit" class="post-delete" value="삭제">
                                    </form>
                                </div>
                            </ul>
                            <span><i class="fas fa-chevron-down"></i></span>
                        </li>
                    </ul>
                </div>
            {% endif %}
            </div>
        </div>
        <div class="imgShow">
            <img src="{{ post.photo.url }}">
        </div>
        <div class="imgPost">
            <div class="id_container">
                <div class="userID">
                    {{ post.author.profile.nickname }}
                </div>
            </div>
            <div class="picLike">
                {% if user in post.like_user_set.all %}
                <!-- class 명 on 으로 해서 값 변경될수 있도록 이미지 분류 필요함 밑에 script_ajax 통신으로 바뀜-->
                <div class="sprite_heart_icon_outline on" name="{{ post.id }}" data-name="heartbeat"><a><i
                            class="fas fa-heart"></i></a><span id="like-count-{{ post.id }}"> {{ post.like_count }} </span></div>
                {% else %}
                <div class="sprite_heart_icon_outline" name="{{ post.id }}" data-name="heartbeat"><a><i
                            class="fas fa-heart"></i></a><span id="like-count-{{ post.id }}"> {{ post.like_count }} </span></div>
                <!--<a><i class="fas fa-heart"></i></a> {{ post.like_count }} 개-->
                {% endif %}

            </div>
            <div class="picReference">
                <div class="sprite_heart_icon_outline on" name="{{ post.id }}" data-name="Reference"><a><i
                            class="far fa-clone"></i></a></div>
                <span id="reference-count-{{ post.id }}"> {{ post.Reference_count }} </span>
            </div>
        </div>
        <div class="postNtag">
            <div class="postTxt">
                {{ post.content }}
            </div>
            <div class="posttag">
                <div class="costag">
                    {{ post.cosmetic }}
                </div>
                <div class="themetag">
                    {{post.tema}}
                </div>
            </div>
        </div>
        <div class="imgComment">
            <div class="comment" id="comment-ajax-post{{post.id}}">
                {% for comment in post.comment_set.all %}
                <div class="comment-detail" id="comment{{ comment.id }}">
                    {% if comment.author.profile.picture.url %}
                    <div class="nick_name"><a href="{% url 'post:post_profile_pk' comment.author.pk %}">
                        <img src="{{ comment.author.profile.picture.url }}"></a>
                        <div class="cmt_all">
                            <span class="cmt_id">{{comment.author.profile.nickname}}</span>
                            {{comment.content}}
                        </div>
                    </div>
                    {% else %}
                    <div class="nick_name"><a href="{% url 'post:post_profile_pk' comment.author.pk %}">
                        <img src="{% static 'img/noprofile.png' %}"></a>
                        <div class="cmt_id">
                            {{comment.author.profile.nickname}}
                            {{comment.content}}
                        </div>

                    </div>
                    {% endif %}
                    {% if user == comment.author %}
                    <input type="button" class="del-comment" data-name="comment_delete" value="삭제"
                        name="{{comment.id}}">
                    {% endif %}

                </div>
                {% endfor %}
            </div>
        </div>
    </div>

    <div class="comment_field" id="add-comment-post{{post.id}}">
        {% if user.is_authenticated %}
        {{ comment_form }}
        <a class="cmticon"><i class="far fa-comment-dots"></i></a>
        <input type="text" placeholder="댓글달기...">
        <div class="upload_btn m_text" name="{{post.id}}" data-name="comment"><i class="fas fa-arrow-up"></i></div>
        {% else %}
        <input type="text" placeholder="댓글달기...">
        <div class="upload_btn m_text" name="{{post.id}}" data-name="comment" onclick="alert('댓글을 작성하려면 로그인이 필요합니다.')">
            <i class="fas fa-arrow-up"></i></div>
        {{ comment_form }}
        {% endif %}
    </div>





    {% include "post/script_ajax.html" %}

    {% endblock %}

backend/django/post/templates/post/post_edit.html
{% extends 'post/base.html' %}
{% load static %}

{% block content %}
<div id ="main_container">

    <div class="post_form_container">
        <form action="" method="post" enctype="multipart/form-data">

            <div class="preview">
                <label for="id_photo">
                    <div class="upload">
                        <div class="post_btn">
                            <div class="plus_icon">
                                <span></span>
                                <span></span>
                            </div>
                        </div>
                    </div>
                </label>
                {% if post %}
                    <p><img id="img_id" src="{{ post.photo.url }}" style="width:300px; height:300px;"></p>
                {% endif %}
            </div>
            {% csrf_token %}
            {{ form.as_p }}

            <input type="submit" class="submit_btn" value="수정하기">
        </form>
    </div>
</div>



<!-- java 업로드 미리 보기-->

<script>
var fileinput = document.querySelector("#id_photo") //url 중 id_photo 의 값을 가져오고
fileinput.addEventListener('change', handleImage);  // 이벤트에 대한 내용을 추적 실행   
var canvas = document.getElementById('imageCanvas') // class 명을 값에 넣고
var ctx = canvas.getContext('2d'); // 값을 불러와라

function handleImage(e){
    var reader = new FileReader();
    reader.onload = function(event){
        var img = new Image();
        img.onload = function(){
            canvas.width = 300;
            canvas.height = 300;
            ctx.drawImage(img,0,0,300,300);
        };
        img.src= event.target.result; // 이미지 경로 지정
    };
    reader.readAsDataURL(e.target.files[0]); //인풋박스에 들어간 이미지를 담아서 출력
};

</script>


{% endblock %}

backend/django/post/templates/post/post_home.html
{% extends "post/layout.html" %}
{% load static %}

{% block content %}
{% endblock %}

backend/django/post/templates/post/post_list.html
{% extends 'post/base.html' %}
{% load static %}
{% block content %}
<form class="searchWindow" action="search_1" method="get">
    <input type="text" name="tag" class="searchInput" placeholder="컨셉TAG, 화장
품 검색" value="{{tag}}" />
    <button class="searchLabel" type="submit"><i class="fas fa-search"></i></button>
</form>

<div class="slide-display">
    <div class="slidePage">
        <div class="imgslide">
            {% for tema in dint_tema %}
            <div class="title">
                <form action="search_1" method="get">
                    <button class="tagBtn" type="submit">
                        {{tema}}
                    </button>
                    <input type="text" name="tag" value="{{tema}}"/>
                </form>
            </div>
            <div class="carousel-container">
                <div class="carousel-slide">
                    {% for post in posts %}
                    {% if tema == post.tema %}
                    <a href="{% url 'post:post_detail' post.pk %}"><img src="{{ post.photo.url }}" alt=""></a>
                    {% endif %}
                    {% endfor %}
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>


{% endblock %}

backend/django/post/templates/post/post_new.html
{% extends "post/base.html" %}
{% load static %}

<!-- java 업로드 미리 보기-->
<script>
var fileinput = document.querySelector("#id_photo") //url 중 id_photo 의 값을 가져오고
fileinput.addEventListener('change', handleImage);  // 이벤트에 대한 내용을 추적 실행   
var canvas = document.getElementById('imageCanvas') // class 명을 값에 넣고
var ctx = canvas.getContext('2d'); // 값을 불러와라

function handleImage(e){
    var reader = new FileReader();
    reader.onload = function(event){
        var img = new Image();
        img.onload = function(){
            canvas.width = 300;
            canvas.height = 300;
            ctx.drawImage(img,0,0,300,300);
        };
        img.src= event.target.result; // 이미지 경로 지정
    };
    reader.readAsDataURL(e.target.files[0]); //인풋박스에 들어간 이미지를 담아서 출력
};
</script>

{% block content %}
    <!-- beautyapp_merged > post > templates > post > post_new.html -->
   <link rel="stylesheet" href="{% static 'css/imgprocess.css' %}"/>

    <form action="" method="post" enctype="multipart/form-data">

        <div class="user-image-container">
            <div class="user-image">
                <img id="showImg" src="{% static picture %}" class="thumnail">
            </div>
        </div>

        {% csrf_token %}
        {{ form.as_p }}

        <input type="submit" class="file-upload-btn-submit" value="  업 로 드" />
        
    </form>
{% endblock %}

backend/django/post/templates/post/profile_ajax.html
<script type="text/javascript">
(function(){
    const delegation = document.querySelector('.content-container');

    function delegationFunc(e) { // 클릭한거 인자로 받음
        let elem = e.target;
        console.log(elem);
        while(!elem.getAttribute('data-name')){
            elem = elem.parentNode;

            if (elem.nodeName == 'BODY'){
                elem = null;
                return;
            }
        }if(elem.matches('[data-name="follow"]')){
            var pk = elem.getAttribute('name');

            $.ajax({
                type: "POST",
                url: "{% url 'accounts:follow' %}",
                data: {
                    'pk': pk,
                    'csrfmiddlewaretoken': '{{ csrf_token}}',
                },
                dataType: "json",
                success: function(response){
                    if(response.status){
                        document.querySelector('input.follow[name=\''+pk+'\']').value="Following";
                    }else{
                        document.querySelector('input.follow[name=\''+pk+'\']').value="Follow";
                    }
                },
                error: function(request, status, error){
                    alert("로그인을 해주세요");
                }
            })

        }

        elem.classList.toggle('on');
    }


    delegation.addEventListener('click',delegationFunc);

})();//익명함수 문서가 로드된후에 자바스크립트가 작동한다.

</script>

backend/django/post/templates/post/test.html
{% extends '/post/base.html' %}
{% load static %}

{% block content %}
    <div class="newsfeed">
        <div class="feedimg">
            <img src="{% static 'img/profile.jpg' %}" alt="">
        </div>
        <div class="event">
            '우주소녀 루다'님이 레퍼런스를 하였습니다.
        </div>
        <div class="targetimg">
            <img src="{% static 'img/1.png' %}" alt="">
        </div>
    </div>
    <div class="newsfeed">
        <div class="feedimg">
            <img src="{% static 'img/profile.jpg' %}" alt="">
        </div>
        <div class="event">
            '우주소녀 루다'님이 게시물을 좋아합니다.
        </div>
        <div class="targetimg">
            <img src="{% static 'img/1.png' %}" alt="">
        </div>
    </div>
{% endblock %}